ALTER TABLE medicines ADD COLUMN IF NOT EXISTS ean13 VARCHAR(32);
ALTER TABLE medicines ADD COLUMN IF NOT EXISTS therapeutic_class VARCHAR(120);
ALTER TABLE medicines ADD COLUMN IF NOT EXISTS form VARCHAR(80);
ALTER TABLE medicines ADD COLUMN IF NOT EXISTS presentation VARCHAR(160);
ALTER TABLE medicines ADD COLUMN IF NOT EXISTS medicine_type VARCHAR(40);
ALTER TABLE medicines ADD COLUMN IF NOT EXISTS note VARCHAR(500);
