-- Arborescence officielle SRM Marrakech-Safi (DG → Direction → Département → Division → Service)
-- Généré par scripts/generate-org-hierarchy-sql.js

DELETE FROM organizational_entities;

INSERT INTO organizational_entities (id, code, name, entity_type, parent_id, deleted) VALUES
    (1000, 'DG-SRM-MS', 'Direction Générale SRM Marrakech-Safi', 'Direction générale', NULL, FALSE),
    (1001, 'DIR-OPE-ELEC', 'Direction Opérationnelle Électricité (Région Marrakech-Safi)', 'Direction', 1000, FALSE),
    (1002, 'DEP-ELEC-RESEAU', 'Département Réseaux et Distribution HT/MT/BT', 'Département', 1001, FALSE),
    (1003, 'DIV-ELEC-HTMT', 'Division Haute et Moyenne Tension (HT/MT)', 'Division', 1002, FALSE),
    (1004, 'SRV-ELEC-COND', 'Service Conduite du Réseau, Dispatching et Téléconduite', 'Service', 1003, FALSE),
    (1005, 'SRV-ELEC-POST', 'Service Maintenance des Postes de Transformation et Postes Sources', 'Service', 1003, FALSE),
    (1006, 'DIV-ELEC-BT', 'Division Basse Tension (BT)', 'Division', 1002, FALSE),
    (1007, 'SRV-ELEC-NEUF', 'Service Travaux Neufs, Extensions et Éclairage Public', 'Service', 1006, FALSE),
    (1008, 'SRV-ELEC-DEP', 'Service Dépannage, Sécurité et Maintenance Curative', 'Service', 1006, FALSE),
    (1009, 'DEP-ELEC-ING', 'Département Ingénierie et Planification Électricité', 'Département', 1001, FALSE),
    (1010, 'DIV-ELEC-ETU', 'Division Études et Projets Réseau', 'Division', 1009, FALSE),
    (1011, 'SRV-ELEC-BE', 'Service Bureau d''Études Électricité et Modélisation', 'Service', 1010, FALSE),
    (1012, 'SRV-ELEC-NORM', 'Service Normalisation, Contrôle de Conformité et Réception', 'Service', 1010, FALSE),
    (1013, 'DIR-OPE-EAU', 'Direction Opérationnelle Eau Potable (Région Marrakech-Safi)', 'Direction', 1000, FALSE),
    (1014, 'DEP-EAU-PROD', 'Département Production, Traitement et Qualité', 'Département', 1013, FALSE),
    (1015, 'DIV-EAU-INFRA', 'Division Infrastructures de Production et Adduction', 'Division', 1014, FALSE),
    (1016, 'SRV-EAU-POMP', 'Service Exploitation des Stations de Pompage et Forages', 'Service', 1015, FALSE),
    (1017, 'SRV-EAU-RES', 'Service Gestion des Réservoirs Principaux et Conduites d''Adduction', 'Service', 1015, FALSE),
    (1018, 'DIV-EAU-LABO', 'Division Laboratoire Régional et Contrôle de Qualité (Marrakech)', 'Division', 1014, FALSE),
    (1019, 'SRV-EAU-PHY', 'Service Analyses Physico-chimiques de l''Eau', 'Service', 1018, FALSE),
    (1020, 'SRV-EAU-BACT', 'Service Analyses Bactériologiques et Vigilance Sanitaire', 'Service', 1018, FALSE),
    (1021, 'DEP-EAU-DIST', 'Département Distribution et Performance Réseau', 'Département', 1013, FALSE),
    (1022, 'DIV-EAU-EXPL', 'Division Exploitation et Maintenance des Réseaux Eau', 'Division', 1021, FALSE),
    (1023, 'SRV-EAU-MAINT', 'Service Maintenance des Conduites, Vannes et Branchements', 'Service', 1022, FALSE),
    (1024, 'DIV-EAU-REND', 'Division Sectorisation et Rendement', 'Division', 1021, FALSE),
    (1025, 'SRV-EAU-FUITE', 'Service Recherche des Fuites et Optimisation des Pressions', 'Service', 1024, FALSE),
    (1026, 'SRV-EAU-RENOV', 'Service Renouvellement des Réseaux Vétustes', 'Service', 1024, FALSE),
    (1027, 'DIR-OPE-ASS', 'Direction Opérationnelle Assainissement Liquide (Région Marrakech-Safi)', 'Direction', 1000, FALSE),
    (1028, 'DEP-ASS-COLL', 'Département Collecte et Réseaux d''Évacuation', 'Département', 1027, FALSE),
    (1029, 'DIV-ASS-ENT', 'Division Entretien et Curage des Réseaux', 'Division', 1028, FALSE),
    (1030, 'SRV-ASS-COLL', 'Service Maintenance des Collecteurs d''Eaux Usées', 'Service', 1029, FALSE),
    (1031, 'SRV-ASS-PLUV', 'Service Gestion, Curage et Protection contre les Crues (Ouvrages Pluviaux)', 'Service', 1029, FALSE),
    (1032, 'DEP-ASS-TRAIT', 'Département Traitement, Épuration et Revalorisation', 'Département', 1027, FALSE),
    (1033, 'DIV-ASS-STEP', 'Division Station d''Épuration (STEP Marrakech et Stations Régionales)', 'Division', 1032, FALSE),
    (1034, 'SRV-ASS-EXPL', 'Service Exploitation et Maintenance Lourde de la STEP', 'Service', 1033, FALSE),
    (1035, 'DIV-ASS-ECO', 'Division Économie Circulaire et Réutilisation', 'Division', 1032, FALSE),
    (1036, 'SRV-ASS-BOUE', 'Service Valorisation des Boues (Biogaz/Agriculture)', 'Service', 1035, FALSE),
    (1037, 'SRV-ASS-REUT', 'Service Traitement Tertiaire et Réutilisation des Eaux Épurées', 'Service', 1035, FALSE),
    (1038, 'DIR-COM', 'Direction Commerciale et Relation Clientèle', 'Direction', 1000, FALSE),
    (1039, 'DEP-COM-FACT', 'Département Gestion des Abonnés et Facturation', 'Département', 1038, FALSE),
    (1040, 'DIV-COM-CPT', 'Division Comptage et Relève', 'Division', 1039, FALSE),
    (1041, 'SRV-COM-CPT', 'Service Pose, Remplacement, Étalonnage et Contrôle des Compteurs', 'Service', 1040, FALSE),
    (1042, 'SRV-COM-REL', 'Service Tournées de Relève des Index et Saisie Mobile', 'Service', 1040, FALSE),
    (1043, 'DIV-COM-FACT', 'Division Facturation et Recouvrement', 'Division', 1039, FALSE),
    (1044, 'SRV-COM-CALC', 'Service Calculs, Audit et Édition des Factures', 'Service', 1043, FALSE),
    (1045, 'SRV-COM-REC', 'Service Recouvrement, Contentieux et Gestion des Impayés', 'Service', 1043, FALSE),
    (1046, 'DEP-COM-RC', 'Département Relation Clientèle et Canaux de Vente', 'Département', 1038, FALSE),
    (1047, 'DIV-COM-AG', 'Division Agences et Front-Office', 'Division', 1046, FALSE),
    (1048, 'SRV-COM-ACC', 'Service Accueil, Gestion et Standardisation des Agences Physiques', 'Service', 1047, FALSE),
    (1049, 'SRV-COM-CRC', 'Service Centre de Relation Client (CRC) et Gestion des Réclamations', 'Service', 1047, FALSE),
    (1050, 'DIV-COM-RACC', 'Division Nouveaux Raccordements et Promoteurs', 'Division', 1046, FALSE),
    (1051, 'SRV-COM-PART', 'Service Raccordement et Branchement des Particuliers', 'Service', 1050, FALSE),
    (1052, 'SRV-COM-GC', 'Service Grands Comptes, Lotisseurs et Zones Industrielles', 'Service', 1050, FALSE),
    (1053, 'DIR-DAF', 'Direction Administrative et Financière', 'Direction', 1000, FALSE),
    (1054, 'DEP-DAF-RH', 'Département Ressources Humaines', 'Département', 1053, FALSE),
    (1055, 'DIV-DAF-ADM', 'Division Administration du Personnel', 'Division', 1054, FALSE),
    (1056, 'SRV-DAF-PAIE', 'Service Gestion Administrative, Contrats et Paie', 'Service', 1055, FALSE),
    (1057, 'SRV-DAF-TPS', 'Service Gestion du Temps, Présences, Congés et Pointage', 'Service', 1055, FALSE),
    (1058, 'DIV-DAF-GPEC', 'Division Gestion Prévisionnelle des Emplois et Compétences (GPEC)', 'Division', 1054, FALSE),
    (1059, 'SRV-DAF-REC', 'Service Recrutement, Intégration et Mobilité Inter-provinces', 'Service', 1058, FALSE),
    (1060, 'SRV-DAF-FORM', 'Service Formation Continue, Évaluation et Gestion des Carrières', 'Service', 1058, FALSE),
    (1061, 'DIV-DAF-SOC', 'Division Affaires Sociales, Hygiène et Sécurité', 'Division', 1054, FALSE),
    (1062, 'SRV-DAF-MUT', 'Service Médecine du Travail, Mutuelle et Assurance Maladie', 'Service', 1061, FALSE),
    (1063, 'SRV-DAF-OEUV', 'Service Œuvres Sociales et Conditions de Travail', 'Service', 1061, FALSE),
    (1064, 'DEP-DAF-FIN', 'Département Finances, Comptabilité et Contrôle de Gestion', 'Département', 1053, FALSE),
    (1065, 'DIV-DAF-CPT', 'Division Comptabilité et Fiscalité', 'Division', 1064, FALSE),
    (1066, 'SRV-DAF-CGEN', 'Service Comptabilité Générale et Fournisseurs', 'Service', 1065, FALSE),
    (1067, 'SRV-DAF-CANA', 'Service Comptabilité Analytique et Déclarations Fiscales', 'Service', 1065, FALSE),
    (1068, 'DIV-DAF-GFIN', 'Division Gestion Financière et Performance', 'Division', 1064, FALSE),
    (1069, 'SRV-DAF-TRES', 'Service Trésorerie, Financements et Relations Bancaires', 'Service', 1068, FALSE),
    (1070, 'SRV-DAF-BUD', 'Service Budgets, Tableaux de Bord et Contrôle de Gestion', 'Service', 1068, FALSE),
    (1071, 'DEP-DAF-ACH', 'Département Achats, Logistique et Moyens Généraux', 'Département', 1053, FALSE),
    (1072, 'DIV-DAF-MARC', 'Division Marchés Publics et Approvisionnements', 'Division', 1071, FALSE),
    (1073, 'SRV-DAF-AO', 'Service Appels d''Offres, Cahiers des Charges (CPS) et Contrats', 'Service', 1072, FALSE),
    (1074, 'SRV-DAF-STK', 'Service Gestion des Stocks, Magasins Centraux et Pièces de Rechange', 'Service', 1072, FALSE),
    (1075, 'DIV-DAF-MG', 'Division Moyens Généraux et Patrimoine', 'Division', 1071, FALSE),
    (1076, 'SRV-DAF-AUTO', 'Service Gestion du Parc Auto régional (Véhicules d''intervention)', 'Service', 1075, FALSE),
    (1077, 'SRV-DAF-PAT', 'Service Entretien du Patrimoine Immobilier, Gardiennage et Nettoyage', 'Service', 1075, FALSE),
    (1078, 'DIR-DSI', 'Direction des Systèmes d''Information et Digitalisation (DSI)', 'Direction', 1000, FALSE),
    (1079, 'DEP-DSI-INFRA', 'Département Infrastructures IT, Systèmes et Cybersécurité', 'Département', 1078, FALSE),
    (1080, 'DIV-DSI-RESEAU', 'Division Réseaux, Systèmes et Télécoms', 'Division', 1079, FALSE),
    (1081, 'SRV-DSI-SRV', 'Service Administration des Serveurs, Datacenter et Cloud', 'Service', 1080, FALSE),
    (1082, 'SRV-DSI-SUP', 'Service Support Utilisateurs et Maintenance du Parc Informatique', 'Service', 1080, FALSE),
    (1083, 'DIV-DSI-SEC', 'Division Sécurité des Systèmes d''Information (SSI)', 'Division', 1079, FALSE),
    (1084, 'SRV-DSI-CYBER', 'Service Cybersécurité, Gestion des Droits et Sauvegardes', 'Service', 1083, FALSE),
    (1085, 'DEP-DSI-APP', 'Département Solutions Applicatives, Données et SIG', 'Département', 1078, FALSE),
    (1086, 'DIV-DSI-PROG', 'Division Progiciels et Applications Métiers', 'Division', 1085, FALSE),
    (1087, 'SRV-DSI-ERP', 'Service ERP Central (Gestion Finance, RH, Achats)', 'Service', 1086, FALSE),
    (1088, 'SRV-DSI-CRM', 'Service Système d''Information Clientèle (Facturation/CRM) et Portails Web/Mobile', 'Service', 1086, FALSE),
    (1089, 'DIV-DSI-SIG', 'Division Systèmes d''Information Géographique (SIG)', 'Division', 1085, FALSE),
    (1090, 'SRV-DSI-CARTO', 'Service Cartographie Digitale, Réseau Connecté et Données Topographiques', 'Service', 1089, FALSE),
    (1091, 'DIR-PROV-MAR', 'Direction Préfectorale de Marrakech', 'Direction', 1000, FALSE),
    (1092, 'PROV-MAR-EXP', 'Département d''Exploitation Préfectorale', 'Département', 1091, FALSE),
    (1093, 'PROV-MAR-EXP-TECH', 'Division Technique Intercommunale', 'Division', 1092, FALSE),
    (1094, 'PROV-MAR-SRV-ELEC', 'Service Réseaux Électricité (Maintenance et Dépannage Local)', 'Service', 1093, FALSE),
    (1095, 'PROV-MAR-SRV-EAU', 'Service Réseaux Eau Potable (Distribution et Réparation des Fuites)', 'Service', 1093, FALSE),
    (1096, 'PROV-MAR-SRV-ASS', 'Service Réseaux Assainissement (Curage et Interventions Urbaines)', 'Service', 1093, FALSE),
    (1097, 'PROV-MAR-COM', 'Département Commercial Provincial', 'Département', 1091, FALSE),
    (1098, 'PROV-MAR-COM-CLI', 'Division Clientèle Locale', 'Division', 1097, FALSE),
    (1099, 'PROV-MAR-SRV-AG', 'Service Agences Locales de Proximité et Guichets', 'Service', 1098, FALSE),
    (1100, 'PROV-MAR-SRV-REL', 'Service Relève des Index, Encaisses et Facturation Provinciale', 'Service', 1098, FALSE),
    (1101, 'PROV-MAR-SUP', 'Département Support Provincial', 'Département', 1091, FALSE),
    (1102, 'PROV-MAR-SUP-LOG', 'Division Logistique et Logistique Territoriale', 'Division', 1101, FALSE),
    (1103, 'PROV-MAR-SRV-MAG', 'Service Magasin Local et Approvisionnement d''Urgence', 'Service', 1102, FALSE),
    (1104, 'PROV-MAR-SRV-PARC', 'Service Maintenance du Parc Auto Provincial', 'Service', 1102, FALSE),
    (1105, 'DIR-PROV-SAF', 'Direction Provinciale de Safi', 'Direction', 1000, FALSE),
    (1106, 'PROV-SAF-EXP', 'Département d''Exploitation Provinciale', 'Département', 1105, FALSE),
    (1107, 'PROV-SAF-EXP-TECH', 'Division Technique Intercommunale', 'Division', 1106, FALSE),
    (1108, 'PROV-SAF-SRV-ELEC', 'Service Réseaux Électricité (Maintenance et Dépannage Local)', 'Service', 1107, FALSE),
    (1109, 'PROV-SAF-SRV-EAU', 'Service Réseaux Eau Potable (Distribution et Réparation des Fuites)', 'Service', 1107, FALSE),
    (1110, 'PROV-SAF-SRV-ASS', 'Service Réseaux Assainissement (Curage et Interventions Urbaines)', 'Service', 1107, FALSE),
    (1111, 'PROV-SAF-COM', 'Département Commercial Provincial', 'Département', 1105, FALSE),
    (1112, 'PROV-SAF-COM-CLI', 'Division Clientèle Locale', 'Division', 1111, FALSE),
    (1113, 'PROV-SAF-SRV-AG', 'Service Agences Locales de Proximité et Guichets', 'Service', 1112, FALSE),
    (1114, 'PROV-SAF-SRV-REL', 'Service Relève des Index, Encaisses et Facturation Provinciale', 'Service', 1112, FALSE),
    (1115, 'PROV-SAF-SUP', 'Département Support Provincial', 'Département', 1105, FALSE),
    (1116, 'PROV-SAF-SUP-LOG', 'Division Logistique et Logistique Territoriale', 'Division', 1115, FALSE),
    (1117, 'PROV-SAF-SRV-MAG', 'Service Magasin Local et Approvisionnement d''Urgence', 'Service', 1116, FALSE),
    (1118, 'PROV-SAF-SRV-PARC', 'Service Maintenance du Parc Auto Provincial', 'Service', 1116, FALSE),
    (1119, 'DIR-PROV-HAO', 'Direction Provinciale d''Al Haouz', 'Direction', 1000, FALSE),
    (1120, 'PROV-HAO-EXP', 'Département d''Exploitation Provinciale', 'Département', 1119, FALSE),
    (1121, 'PROV-HAO-EXP-TECH', 'Division Technique Intercommunale', 'Division', 1120, FALSE),
    (1122, 'PROV-HAO-SRV-ELEC', 'Service Réseaux Électricité (Maintenance et Dépannage Local)', 'Service', 1121, FALSE),
    (1123, 'PROV-HAO-SRV-EAU', 'Service Réseaux Eau Potable (Distribution et Réparation des Fuites)', 'Service', 1121, FALSE),
    (1124, 'PROV-HAO-SRV-ASS', 'Service Réseaux Assainissement (Curage et Interventions Urbaines)', 'Service', 1121, FALSE),
    (1125, 'PROV-HAO-COM', 'Département Commercial Provincial', 'Département', 1119, FALSE),
    (1126, 'PROV-HAO-COM-CLI', 'Division Clientèle Locale', 'Division', 1125, FALSE),
    (1127, 'PROV-HAO-SRV-AG', 'Service Agences Locales de Proximité et Guichets', 'Service', 1126, FALSE),
    (1128, 'PROV-HAO-SRV-REL', 'Service Relève des Index, Encaisses et Facturation Provinciale', 'Service', 1126, FALSE),
    (1129, 'PROV-HAO-SUP', 'Département Support Provincial', 'Département', 1119, FALSE),
    (1130, 'PROV-HAO-SUP-LOG', 'Division Logistique et Logistique Territoriale', 'Division', 1129, FALSE),
    (1131, 'PROV-HAO-SRV-MAG', 'Service Magasin Local et Approvisionnement d''Urgence', 'Service', 1130, FALSE),
    (1132, 'PROV-HAO-SRV-PARC', 'Service Maintenance du Parc Auto Provincial', 'Service', 1130, FALSE),
    (1133, 'DIR-PROV-KEL', 'Direction Provinciale d''El Kelaâ des Sraghna', 'Direction', 1000, FALSE),
    (1134, 'PROV-KEL-EXP', 'Département d''Exploitation Provinciale', 'Département', 1133, FALSE),
    (1135, 'PROV-KEL-EXP-TECH', 'Division Technique Intercommunale', 'Division', 1134, FALSE),
    (1136, 'PROV-KEL-SRV-ELEC', 'Service Réseaux Électricité (Maintenance et Dépannage Local)', 'Service', 1135, FALSE),
    (1137, 'PROV-KEL-SRV-EAU', 'Service Réseaux Eau Potable (Distribution et Réparation des Fuites)', 'Service', 1135, FALSE),
    (1138, 'PROV-KEL-SRV-ASS', 'Service Réseaux Assainissement (Curage et Interventions Urbaines)', 'Service', 1135, FALSE),
    (1139, 'PROV-KEL-COM', 'Département Commercial Provincial', 'Département', 1133, FALSE),
    (1140, 'PROV-KEL-COM-CLI', 'Division Clientèle Locale', 'Division', 1139, FALSE),
    (1141, 'PROV-KEL-SRV-AG', 'Service Agences Locales de Proximité et Guichets', 'Service', 1140, FALSE),
    (1142, 'PROV-KEL-SRV-REL', 'Service Relève des Index, Encaisses et Facturation Provinciale', 'Service', 1140, FALSE),
    (1143, 'PROV-KEL-SUP', 'Département Support Provincial', 'Département', 1133, FALSE),
    (1144, 'PROV-KEL-SUP-LOG', 'Division Logistique et Logistique Territoriale', 'Division', 1143, FALSE),
    (1145, 'PROV-KEL-SRV-MAG', 'Service Magasin Local et Approvisionnement d''Urgence', 'Service', 1144, FALSE),
    (1146, 'PROV-KEL-SRV-PARC', 'Service Maintenance du Parc Auto Provincial', 'Service', 1144, FALSE),
    (1147, 'DIR-PROV-ESS', 'Direction Provinciale d''Essaouira', 'Direction', 1000, FALSE),
    (1148, 'PROV-ESS-EXP', 'Département d''Exploitation Provinciale', 'Département', 1147, FALSE),
    (1149, 'PROV-ESS-EXP-TECH', 'Division Technique Intercommunale', 'Division', 1148, FALSE),
    (1150, 'PROV-ESS-SRV-ELEC', 'Service Réseaux Électricité (Maintenance et Dépannage Local)', 'Service', 1149, FALSE),
    (1151, 'PROV-ESS-SRV-EAU', 'Service Réseaux Eau Potable (Distribution et Réparation des Fuites)', 'Service', 1149, FALSE),
    (1152, 'PROV-ESS-SRV-ASS', 'Service Réseaux Assainissement (Curage et Interventions Urbaines)', 'Service', 1149, FALSE),
    (1153, 'PROV-ESS-COM', 'Département Commercial Provincial', 'Département', 1147, FALSE),
    (1154, 'PROV-ESS-COM-CLI', 'Division Clientèle Locale', 'Division', 1153, FALSE),
    (1155, 'PROV-ESS-SRV-AG', 'Service Agences Locales de Proximité et Guichets', 'Service', 1154, FALSE),
    (1156, 'PROV-ESS-SRV-REL', 'Service Relève des Index, Encaisses et Facturation Provinciale', 'Service', 1154, FALSE),
    (1157, 'PROV-ESS-SUP', 'Département Support Provincial', 'Département', 1147, FALSE),
    (1158, 'PROV-ESS-SUP-LOG', 'Division Logistique et Logistique Territoriale', 'Division', 1157, FALSE),
    (1159, 'PROV-ESS-SRV-MAG', 'Service Magasin Local et Approvisionnement d''Urgence', 'Service', 1158, FALSE),
    (1160, 'PROV-ESS-SRV-PARC', 'Service Maintenance du Parc Auto Provincial', 'Service', 1158, FALSE),
    (1161, 'DIR-PROV-REH', 'Direction Provinciale de Rehamna', 'Direction', 1000, FALSE),
    (1162, 'PROV-REH-EXP', 'Département d''Exploitation Provinciale', 'Département', 1161, FALSE),
    (1163, 'PROV-REH-EXP-TECH', 'Division Technique Intercommunale', 'Division', 1162, FALSE),
    (1164, 'PROV-REH-SRV-ELEC', 'Service Réseaux Électricité (Maintenance et Dépannage Local)', 'Service', 1163, FALSE),
    (1165, 'PROV-REH-SRV-EAU', 'Service Réseaux Eau Potable (Distribution et Réparation des Fuites)', 'Service', 1163, FALSE),
    (1166, 'PROV-REH-SRV-ASS', 'Service Réseaux Assainissement (Curage et Interventions Urbaines)', 'Service', 1163, FALSE),
    (1167, 'PROV-REH-COM', 'Département Commercial Provincial', 'Département', 1161, FALSE),
    (1168, 'PROV-REH-COM-CLI', 'Division Clientèle Locale', 'Division', 1167, FALSE),
    (1169, 'PROV-REH-SRV-AG', 'Service Agences Locales de Proximité et Guichets', 'Service', 1168, FALSE),
    (1170, 'PROV-REH-SRV-REL', 'Service Relève des Index, Encaisses et Facturation Provinciale', 'Service', 1168, FALSE),
    (1171, 'PROV-REH-SUP', 'Département Support Provincial', 'Département', 1161, FALSE),
    (1172, 'PROV-REH-SUP-LOG', 'Division Logistique et Logistique Territoriale', 'Division', 1171, FALSE),
    (1173, 'PROV-REH-SRV-MAG', 'Service Magasin Local et Approvisionnement d''Urgence', 'Service', 1172, FALSE),
    (1174, 'PROV-REH-SRV-PARC', 'Service Maintenance du Parc Auto Provincial', 'Service', 1172, FALSE),
    (1175, 'DIR-PROV-CHI', 'Direction Provinciale de Chichaoua', 'Direction', 1000, FALSE),
    (1176, 'PROV-CHI-EXP', 'Département d''Exploitation Provinciale', 'Département', 1175, FALSE),
    (1177, 'PROV-CHI-EXP-TECH', 'Division Technique Intercommunale', 'Division', 1176, FALSE),
    (1178, 'PROV-CHI-SRV-ELEC', 'Service Réseaux Électricité (Maintenance et Dépannage Local)', 'Service', 1177, FALSE),
    (1179, 'PROV-CHI-SRV-EAU', 'Service Réseaux Eau Potable (Distribution et Réparation des Fuites)', 'Service', 1177, FALSE),
    (1180, 'PROV-CHI-SRV-ASS', 'Service Réseaux Assainissement (Curage et Interventions Urbaines)', 'Service', 1177, FALSE),
    (1181, 'PROV-CHI-COM', 'Département Commercial Provincial', 'Département', 1175, FALSE),
    (1182, 'PROV-CHI-COM-CLI', 'Division Clientèle Locale', 'Division', 1181, FALSE),
    (1183, 'PROV-CHI-SRV-AG', 'Service Agences Locales de Proximité et Guichets', 'Service', 1182, FALSE),
    (1184, 'PROV-CHI-SRV-REL', 'Service Relève des Index, Encaisses et Facturation Provinciale', 'Service', 1182, FALSE),
    (1185, 'PROV-CHI-SUP', 'Département Support Provincial', 'Département', 1175, FALSE),
    (1186, 'PROV-CHI-SUP-LOG', 'Division Logistique et Logistique Territoriale', 'Division', 1185, FALSE),
    (1187, 'PROV-CHI-SRV-MAG', 'Service Magasin Local et Approvisionnement d''Urgence', 'Service', 1186, FALSE),
    (1188, 'PROV-CHI-SRV-PARC', 'Service Maintenance du Parc Auto Provincial', 'Service', 1186, FALSE),
    (1189, 'DIR-PROV-YOU', 'Direction Provinciale de Youssoufia', 'Direction', 1000, FALSE),
    (1190, 'PROV-YOU-EXP', 'Département d''Exploitation Provinciale', 'Département', 1189, FALSE),
    (1191, 'PROV-YOU-EXP-TECH', 'Division Technique Intercommunale', 'Division', 1190, FALSE),
    (1192, 'PROV-YOU-SRV-ELEC', 'Service Réseaux Électricité (Maintenance et Dépannage Local)', 'Service', 1191, FALSE),
    (1193, 'PROV-YOU-SRV-EAU', 'Service Réseaux Eau Potable (Distribution et Réparation des Fuites)', 'Service', 1191, FALSE),
    (1194, 'PROV-YOU-SRV-ASS', 'Service Réseaux Assainissement (Curage et Interventions Urbaines)', 'Service', 1191, FALSE),
    (1195, 'PROV-YOU-COM', 'Département Commercial Provincial', 'Département', 1189, FALSE),
    (1196, 'PROV-YOU-COM-CLI', 'Division Clientèle Locale', 'Division', 1195, FALSE),
    (1197, 'PROV-YOU-SRV-AG', 'Service Agences Locales de Proximité et Guichets', 'Service', 1196, FALSE),
    (1198, 'PROV-YOU-SRV-REL', 'Service Relève des Index, Encaisses et Facturation Provinciale', 'Service', 1196, FALSE),
    (1199, 'PROV-YOU-SUP', 'Département Support Provincial', 'Département', 1189, FALSE),
    (1200, 'PROV-YOU-SUP-LOG', 'Division Logistique et Logistique Territoriale', 'Division', 1199, FALSE),
    (1201, 'PROV-YOU-SRV-MAG', 'Service Magasin Local et Approvisionnement d''Urgence', 'Service', 1200, FALSE),
    (1202, 'PROV-YOU-SRV-PARC', 'Service Maintenance du Parc Auto Provincial', 'Service', 1200, FALSE);

SELECT setval(pg_get_serial_sequence('organizational_entities', 'id'), (SELECT MAX(id) FROM organizational_entities));

-- Aligner quelques agents démo sur la nouvelle structure (mutuelle / DSI)
UPDATE agents SET entite_name = 'Service Médecine du Travail, Mutuelle et Assurance Maladie'
WHERE matricule IN ('AGT-001', 'AGT-002', 'AGT-007', 'AGT-008');

UPDATE agents SET entite_name = 'Service Système d''Information Clientèle (Facturation/CRM) et Portails Web/Mobile'
WHERE matricule IN ('AGT-004', 'AGT-006');

UPDATE agents SET entite_name = 'Direction Opérationnelle Électricité (Région Marrakech-Safi)'
WHERE matricule = 'AGT-003';

UPDATE agents SET entite_name = 'Direction Commerciale et Relation Clientèle'
WHERE matricule = 'AGT-005';
